"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

fibs = [0, 1]

while(fibs[-1] < 4000000):
    fibs.append(fibs[-2] + fibs[-1])
    
print sum(f for f in fibs if f % 2 == 0)