"""
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math

def find_factors(n):
    factors = []
    max = int(math.floor(math.sqrt(n)))
    for x in range(1, max + 1):
        if n % x == 0:
            factors.append(x)
            
            if n != x:
                factors.append(n / x)
        
    return sorted(factors)

def triangle_num(n):
    return sum(range(0,n + 1))

found = False

i = 1
while not found:
    tn = triangle_num(i)
    
    factors = find_factors(tn)
    
    if len(factors) > 500:
        print tn
        found = True
    
    i += 1